Acm:
  dim: 64
  method: "gat"
  attn_drop: 0.9
  feat_drop: 0.9
  alpha: 1
  dropout: 0.0
  long_mask_rate: 0.37
  short_mask_rate: 0.09
  metapath_layers: 1
  heads: 1
  noise_rate: 0.36
  gat_drop: 0.1
  epoch: 400
  lr: 0.008
  wd: 0.0
DBLP:
  dim: 128
  method: "gat"
  attn_drop: 0.2
  feat_drop: 0.2
  alpha: 1
  dropout: 0.0
  long_mask_rate: 0.75
  short_mask_rate: 0.79
  metapath_layers: 1
  heads: 4
  noise_rate: 0.38
  gat_drop: 0.4
  epoch: 400
  lr: 0.015
  wd: 0.0
IMDB:
  dim: 64
  method: "mean"
  attn_drop: 0.4
  feat_drop: 0.1
  alpha: 1
  dropout: 0.1
  long_mask_rate: 0.97
  short_mask_rate: 0.83
  metapath_layers: 1
  heads: 4
  noise_rate: 0.04
  gat_drop: 0.0
  epoch: 200
  lr: 0.004
  wd: 0.0
Freebase:
  dim: 128
  method: "max"
  attn_drop: 0.5
  feat_drop: 0.2
  alpha: 1
  dropout: 0.1
  long_mask_rate: 0.36
  short_mask_rate: 0.65
  metapath_layers: 2
  heads: 4,
  noise_rate: 0.29
  gat_drop: 0.0
  epoch: 200
  lr: 0.081
  wd: 0.0
Aminer:
  dim: 64
  method: "mean"
  attn_drop: 0.4
  feat_drop: 0.9
  alpha: 1
  dropout: 0.5
  long_mask_rate: 0.87
  short_mask_rate: 0.68
  metapath_layers: 2
  heads: 4
  noise_rate: 0.1
  gat_drop: 0.1
  epoch: 300
  lr: 0.014
  wd: 0.0