Acm:
  dim: 128
  method: "gat"
  attn_drop: 0.9
  feat_drop: 0.4
  alpha: 1
  dropout: 0.0
  long_mask_rate: 0.75
  short_mask_rate: 0.68
  metapath_layers: 1
  heads: 4
  noise_rate: 0.34
  gat_drop: 0.0
  epoch: 500
  lr: 0.004
  lr1: 0.01
  wd: 0.0
DBLP:
  dim: 128
  method: "gat"
  attn_drop: 0.9
  feat_drop: 0.8
  alpha: 1
  dropout: 0.5
  long_mask_rate: 0.87
  short_mask_rate: 0.79
  metapath_layers: 1
  heads: 4
  noise_rate: 0.49
  gat_drop: 0.0
  epoch: 300
  lr: 0.013
  lr1: 0.01
  wd: 0.0
Freebase:
  dim: 128
  method: "max"
  attn_drop: 0.9
  feat_drop: 0.8
  alpha: 1
  dropout: 0.7
  long_mask_rate: 0.6
  short_mask_rate: 0.75
  metapath_layers: 1
  heads: 4,
  noise_rate: 0.16
  gat_drop: 0.0
  epoch: 300
  lr: 0.038
  lr1: 0.081
  wd: 0.0
IMDB:
  dim: 64
  method: "gat"
  attn_drop: 0.0
  feat_drop: 0.5
  alpha: 1
  dropout: 0.4
  long_mask_rate: 0.94
  short_mask_rate: 0.85
  metapath_layers: 1
  heads: 4
  noise_rate: 0.04
  gat_drop: 0.0
  epoch: 300
  lr: 0.001
  lr1: 0.01
  wd: 0.0
Aminer:
  dim: 128
  method: "mean"
  attn_drop: 0.7
  feat_drop: 0.7
  alpha: 1
  dropout: 0.4
  long_mask_rate: 0.05
  short_mask_rate: 0.82
  metapath_layers: 2
  heads: 1
  noise_rate: 0.17
  gat_drop: 0.1
  epoch: 300
  lr: 0.003
  lr1: 0.01
  wd: 0.0